// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelConversion():Promise<void>;

export function ClearLaunchRequest():Promise<void>;

export function GetFileSizes(arg1:Array<string>):Promise<Array<number>>;

export function GetFormats():Promise<Array<main.FormatOption>>;

export function GetLaunchRequest():Promise<main.LaunchRequest>;

export function GetSettings():Promise<main.Settings>;

export function HideWindow():Promise<void>;

export function IsExplorerIntegrationRegistered():Promise<boolean>;

export function OpenCodecStore():Promise<void>;

export function OpenSettings():Promise<void>;

export function PreviewFile(arg1:string):Promise<string>;

export function Quit():Promise<void>;

export function RegisterExplorerIntegration():Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function ShowWindow():Promise<void>;

export function StartConversion(arg1:Array<string>,arg2:main.ConversionOptions):Promise<void>;

export function UnregisterExplorerIntegration():Promise<void>;
