// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelConversion() {
  return window['go']['main']['App']['CancelConversion']();
}

export function ClearLaunchRequest() {
  return window['go']['main']['App']['ClearLaunchRequest']();
}

export function GetFileSizes(arg1) {
  return window['go']['main']['App']['GetFileSizes'](arg1);
}

export function GetFormats() {
  return window['go']['main']['App']['GetFormats']();
}

export function GetLaunchRequest() {
  return window['go']['main']['App']['GetLaunchRequest']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsExplorerIntegrationRegistered() {
  return window['go']['main']['App']['IsExplorerIntegrationRegistered']();
}

export function OpenCodecStore() {
  return window['go']['main']['App']['OpenCodecStore']();
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function PreviewFile(arg1) {
  return window['go']['main']['App']['PreviewFile'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RegisterExplorerIntegration() {
  return window['go']['main']['App']['RegisterExplorerIntegration']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartConversion(arg1, arg2) {
  return window['go']['main']['App']['StartConversion'](arg1, arg2);
}

export function UnregisterExplorerIntegration() {
  return window['go']['main']['App']['UnregisterExplorerIntegration']();
}
